### ISSUE TITLE
Update carousel images

### ISSUE THREAD

**Issue by cbcunc** [RENCI/xDCIShare#10]
In theme/static/image/home-page/carousel, update bg1.pjg, bg2.jpg, bg3.jpg as per @rayi113.

**Comment by cbcunc** [comment]
Images from pixbay, all CC0 Public Domain:

    https://pixabay.com/en/dna-string-biology-3d-1811955/
    https://pixabay.com/en/cells-human-medical-biology-health-1872666/
    https://pixabay.com/en/hurricane-earth-satellite-tracking-92968/

**Comment by rayi113** [comment]
Could I suggest using this as one of the 3 images:
https://commons.wikimedia.org/wiki/File:Researcher_looks_through_microscope_(1).jpg
![researcher_looks_through_microscope_02](https://cloud.githubusercontent.com/assets/2846017/26112947/3410aac6-3a27-11e7-9142-6fa717c31280.png)

**Comment by cbcunc** [comment]
Merged in #18 and #22. (Revert accidental merge into develop instead of xdci-develop in #21).
