### ISSUE TITLE
Install new logos

### ISSUE THREAD

**Issue by cbcunc** [RENCI/xDCIShare#45]
Get new logos from Kelsey and/or Cesar.

**Comment by cbcunc** [comment]
Merged in #48.

**Comment by rayi113** [comment]
I'm not able to see the new logo on xDCIShare.renci.org after clearing my browser cache.

**Comment by cbcunc** [comment]
No, it hasn't been deployed to xDCIShare.renci.org yet. It's just fixed in GitHub.

**Comment by cbcunc** [comment]
Deployed to xdcishare.renci.org.
