### ISSUE TITLE
Remove APPS tab until functional

### ISSUE THREAD

**Issue by rayi113** [RENCI/xDCIShare#50]
How difficult is it to remove the "APPS" tab between "COLLABORATE" and "HELP" until it is functional?  Or (less desirable) redirect it to a webpage saying feature forthcoming in future release?

![xdci_apps_tab](https://user-images.githubusercontent.com/2846017/28039953-16d714d6-6592-11e7-8dc4-776b512ef0a7.png)

**Comment by mjstealey** [comment]
It's a mezzanine page so it can just be put into "draft" mode and will no longer display to regular users. Will still show for admin level users though.

![screen shot 2017-07-10 at 7 08 23 pm](https://user-images.githubusercontent.com/5332509/28044085-510f563e-65a3-11e7-89ed-7cf9206e8756.png)

**Comment by rayi113** [comment]
Great, thanks.

**Comment by cbcunc** [comment]
Merged into the default database in #57.
